#!/bin/sh

set -e
export APACHE_RUN_USER=site
export APACHE_RUN_GROUP=site
export APACHE_PID_FILE=/var/run/apache2.pid
export APACHE_RUN_DIR=/var/run/apache2
export APACHE_LOCK_DIR=/var/lock/apache2
export APACHE_LOG_DIR=/var/log/apache2/sites
export APACHE_SERVER_NAME localhost

export LANG=C
export LANG

exec /usr/sbin/httpd -DNO_DETACH -f /etc/apache2/httpd.conf

